service: 'auction-service'
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-stack-output
  - serverless-prune-plugin
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${env:ENVORONMENT, 'dev'}
  memorySize: 128
  environment:
    AUCTIONS_TABLE_NAME: AuctionsTable
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:UpdateItem
      Resource:
        - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/AuctionsTable

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
functions:
  createAuction:
    handler: src/functions/createAuction/index.handler
    events:
      - http:
          method: POST
          path: /auction
  getAuctions:
    handler: src/functions/getAuctions/index.handler
    events:
      - http:
          method: GET
          path: /auctions
  getAuction:
    handler: src/functions/getAuction/index.handler
    events:
      - http:
          method: GET
          path: /auction/{id}
  placeBid:
    handler: src/functions/placeBid/index.handler
    events:
      - http:
          method: PATCH
          path: /auction/{id}/bid
custom:
  bundle:
    linting: false
  webpack:
    webpackConfig: './webpack.config.js'
  packager: yarn
  excludeFiles: src/**/*.test.ts
