service: 'auction-service'
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  - serverless-stack-output
  - serverless-prune-plugin
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: ${env:ENVORONMENT, 'dev'}
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/AuctionsTable

resources:
  Resources:
    AuctionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: AuctionsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
functions:
  createAuction:
    handler: src/functions/createAuction/index.handler
    events:
      - http:
          method: POST
          path: /auction
custom:
  bundle:
    linting: false
  webpack:
    webpackConfig: './webpack.config.js'
  packager: yarn
  excludeFiles: src/**/*.test.ts
